package tech.thessemaj.lspmodule

import android.util.Log
import de.robv.android.xposed.IXposedHookLoadPackage
import de.robv.android.xposed.XC_MethodHook
import de.robv.android.xposed.XposedBridge
import de.robv.android.xposed.XposedHelpers
import de.robv.android.xposed.callbacks.XC_LoadPackage

/**
 * LSPosed entry point declared by `assets/xposed_init`. The real
 * Xposed framework instantiates this class once per target
 * process and calls [handleLoadPackage] from inside the host
 * process's classloader, so any reflection here resolves against
 * the *target* app's class graph.
 *
 * What this module does:
 *   1. When `tech.thessemaj.sample` loads, install hooks on the four
 *      most commonly-called DeviceIntelligence public API entry
 *      points (the "@Critical" methods).
 *   2. Every hook callback only logs — it does not modify
 *      arguments or results. That's enough: the mere presence of
 *      LSPosed's dispatcher (`de.robv.android.xposed.XposedBridge.
 *      handleHookedMethod`) on the call stack of one of those
 *      methods is what `StackGuard.verify()` matches against the
 *      framework denylist, lifting it into a `stack_foreign_frame`
 *      finding.
 *
 * What this module does NOT do:
 *   - It does not hook native code. G7 (`native_caller_out_of_
 *     range`) requires a native trampoline (Frida / libsubstrate);
 *     LSPosed is a Java-side method-hook framework.
 *   - It does not patch `libdicore.so`. G2 (text drift) and G4
 *     (GOT drift) won't fire from this module alone.
 */
class MainHook : IXposedHookLoadPackage {

    override fun handleLoadPackage(lpparam: XC_LoadPackage.LoadPackageParam) {
        // Scope guard: even with `xposedscope` declared in the
        // manifest, a misconfigured user could enable the module
        // globally; bailing here keeps us out of every other
        // process on the device.
        if (lpparam.packageName != TARGET_PACKAGE) return

        XposedBridge.log("[$TAG] hooking $TARGET_PACKAGE")
        Log.i(TAG, "hooking DeviceIntelligence in $TARGET_PACKAGE")

        // Hook each of the four DeviceIntelligence entry points
        // the sample app uses. Two are suspend functions whose
        // generated bytecode signature ends in `(Continuation)`;
        // the blocking pair are direct.
        hookSafely(
            description = "DeviceIntelligence.collect(Context, Continuation)",
        ) {
            XposedHelpers.findAndHookMethod(
                DI_CLASS,
                lpparam.classLoader,
                "collect",
                "android.content.Context",
                "kotlin.coroutines.Continuation",
                logOnlyHook("collect"),
            )
        }
        hookSafely(
            description = "DeviceIntelligence.collectJson(Context, Continuation)",
        ) {
            XposedHelpers.findAndHookMethod(
                DI_CLASS,
                lpparam.classLoader,
                "collectJson",
                "android.content.Context",
                "kotlin.coroutines.Continuation",
                logOnlyHook("collectJson"),
            )
        }
        hookSafely(
            description = "DeviceIntelligence.collectBlocking(Context, CollectOptions)",
        ) {
            XposedHelpers.findAndHookMethod(
                DI_CLASS,
                lpparam.classLoader,
                "collectBlocking",
                "android.content.Context",
                "tech.thessemaj.deviceintelligence.CollectOptions",
                logOnlyHook("collectBlocking"),
            )
        }
        hookSafely(
            description = "DeviceIntelligence.collectJsonBlocking(Context)",
        ) {
            XposedHelpers.findAndHookMethod(
                DI_CLASS,
                lpparam.classLoader,
                "collectJsonBlocking",
                "android.content.Context",
                logOnlyHook("collectJsonBlocking"),
            )
        }
    }

    private inline fun hookSafely(description: String, action: () -> Unit) {
        try {
            action()
            XposedBridge.log("[$TAG] hooked $description")
        } catch (t: Throwable) {
            // A version mismatch / signature drift in DI shouldn't
            // crash the host process — log and move on.
            XposedBridge.log("[$TAG] hook FAILED for $description: ${t.javaClass.name}: ${t.message}")
        }
    }

    private fun logOnlyHook(label: String): XC_MethodHook = object : XC_MethodHook() {
        override fun beforeHookedMethod(param: MethodHookParam) {
            // Triggers GENERATE-side: by the time DI's `verify()`
            // runs (first line of the original method), our
            // `LSPHooker_<method>` and
            // `de.robv.android.xposed.XposedBridge` frames are
            // already on the stack above it.
            XposedBridge.log("[$TAG] before $label")
        }
        override fun afterHookedMethod(param: MethodHookParam) {
            XposedBridge.log("[$TAG] after $label (result=${param.result?.javaClass?.simpleName})")
        }
    }

    private companion object {
        const val TAG = "DI-LSPModule"
        const val TARGET_PACKAGE = "tech.thessemaj.sample"
        const val DI_CLASS = "tech.thessemaj.deviceintelligence.DeviceIntelligence"
    }
}
