plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

// Minimal LSPosed (Xposed) module used purely to verify
// DeviceIntelligence's anti-hooking detectors (G5 StackGuard /
// G6 StackWatchdog). It hooks the public DeviceIntelligence API
// surface so that XposedBridge / LSPHooker frames appear on the
// stack of `StackGuard.verify()`, which the runtime then lifts
// into `stack_foreign_frame` findings.
//
// This module is NOT shipped to consumers and intentionally has
// no dependency on the DeviceIntelligence library. It is
// installed alongside the sample app on a rooted, LSPosed-
// enabled device, then activated and scoped to
// `tech.thessemaj.sample` via the LSPosed Manager UI.
android {
    namespace = "tech.thessemaj.lspmodule"
    compileSdk = 36

    defaultConfig {
        applicationId = "tech.thessemaj.lspmodule"
        minSdk = 28
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    // CompileOnly: the LSPosed framework supplies the real
    // implementation at runtime. If this were `implementation`
    // the stub classes would be packaged into the dex and shadow
    // the framework's classes, breaking every hook.
    compileOnly(project(":samples:xposed-api-stubs"))
}

// CTF Flag 1 — bake the prebuilt DEX payload at
// `tools/red-team/flag1-payload/payload.dex` into a generated
// Kotlin object so DexInjectionHook can `ByteBuffer.wrap(...)` it
// without doing any disk I/O at runtime. The payload.dex file is
// regenerated by `tools/red-team/flag1-payload/build-payload.sh`
// and checked into the repo (~772 bytes).
val flag1PayloadFile = rootProject.file("tools/red-team/flag1-payload/payload.dex")
val flag1GeneratedDir = layout.buildDirectory.dir("generated/source/flag1payload/main")

val bakeFlag1Payload by tasks.registering {
    inputs.file(flag1PayloadFile)
    outputs.dir(flag1GeneratedDir)
    doLast {
        if (!flag1PayloadFile.exists()) {
            throw GradleException(
                "missing payload.dex — run tools/red-team/flag1-payload/build-payload.sh first " +
                    "(expected at ${flag1PayloadFile.absolutePath})",
            )
        }
        val bytes = flag1PayloadFile.readBytes()
        val target = flag1GeneratedDir.get()
            .file("tech/thessemaj/lspmodule/Flag1Payload.kt")
            .asFile
        target.parentFile.mkdirs()
        target.writeText(buildString {
            append("// Generated from tools/red-team/flag1-payload/payload.dex — do not edit.\n")
            append("// Regenerate by re-running build-payload.sh; the bakeFlag1Payload\n")
            append("// Gradle task picks up the new bytes automatically.\n")
            append("package tech.thessemaj.lspmodule\n\n")
            append("internal object Flag1Payload {\n")
            append("    /** Raw DEX bytes for the CTF Flag 1 payload class. */\n")
            append("    internal val BAKED_DEX: ByteArray = byteArrayOf(\n        ")
            bytes.forEachIndexed { i, b ->
                append(b.toInt().toString())
                if (i < bytes.size - 1) append(", ")
                if ((i + 1) % 16 == 0 && i < bytes.size - 1) append("\n        ")
            }
            append("\n    )\n}\n")
        })
    }
}

// Wire the generated source into the main Kotlin source set and
// make the Kotlin compile depend on the bake task.
android.sourceSets.named("main") {
    kotlin.srcDir(flag1GeneratedDir)
}
afterEvaluate {
    tasks.matching { it.name.startsWith("compile") && it.name.endsWith("Kotlin") }
        .configureEach { dependsOn(bakeFlag1Payload) }
}
