package tech.thessemaj.deviceintelligence.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Emits a tiny `AndroidManifest.xml` fragment containing only the
 * permissions the consumer opted into via the `deviceintelligence`
 * Gradle DSL block (e.g. `enableVpnDetection = true`).
 *
 * The fragment is wired into the consumer's variant manifest pipeline
 * via `variant.sources.manifests.addGeneratedManifestFile`, so AGP's
 * manifest merger picks it up at the highest priority and the
 * permission ends up in the final APK without the consumer touching
 * their own `AndroidManifest.xml`.
 *
 * Why a per-permission flag (and not a single "permissive mode"):
 * each opt-in here is a Play Store contract decision the consumer
 * needs to make individually — `ACCESS_NETWORK_STATE` is benign,
 * but future opt-ins (e.g. `READ_PHONE_STATE` for richer telephony
 * cohorting) absolutely are not, and we do not want to bundle them.
 */
@CacheableTask
abstract class GenerateOptionalManifestTask : DefaultTask() {

    /** True iff `enableVpnDetection = true` in the consumer's DSL. */
    @get:Input
    abstract val needsAccessNetworkState: Property<Boolean>

    /** True iff `enableBiometricsDetection = true` in the consumer's DSL. */
    @get:Input
    abstract val needsUseBiometric: Property<Boolean>

    /**
     * Variant name, baked in only for diagnostic output / cache key
     * differentiation across multi-variant builds.
     */
    @get:Input
    abstract val variantName: Property<String>

    /**
     * Generated manifest fragment. Wired into the variant's manifest
     * sources by [tech.thessemaj.deviceintelligence.gradle.DeviceIntelligencePlugin].
     */
    @get:OutputFile
    abstract val outputManifest: RegularFileProperty

    @TaskAction
    fun generate() {
        val out = outputManifest.get().asFile
        out.parentFile?.mkdirs()
        val perms = buildList {
            if (needsAccessNetworkState.getOrElse(false)) add(ACCESS_NETWORK_STATE)
            if (needsUseBiometric.getOrElse(false)) add(USE_BIOMETRIC)
        }
        // We always write a valid manifest, even when no permissions
        // are opted in, so AGP's manifest merger always finds the
        // file we declared via addGeneratedManifestFile and never
        // fails on a missing-file error mid-build.
        val xml = buildString {
            append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
            append("<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">\n")
            append("    <!-- Generated by tech.thessemaj.deviceintelligence Gradle plugin (variant=")
            append(variantName.getOrElse("?"))
            append("). DO NOT EDIT. -->\n")
            for (p in perms) {
                append("    <uses-permission android:name=\"")
                append(p)
                append("\" />\n")
            }
            append("</manifest>\n")
        }
        out.writeText(xml)
        logger.info(
            "tech.thessemaj: wrote optional manifest to ${out.absolutePath} " +
                "(${perms.size} permission(s))"
        )
    }

    private companion object {
        const val ACCESS_NETWORK_STATE = "android.permission.ACCESS_NETWORK_STATE"
        const val USE_BIOMETRIC = "android.permission.USE_BIOMETRIC"
    }
}
