import java.util.Properties

plugins {
    `kotlin-dsl`
    `java-gradle-plugin`
    `maven-publish`
}

// Single source of truth: the parent build's gradle.properties. We're an
// included build, so we don't inherit the parent's properties through the
// usual `providers.gradleProperty(...)` channel; loading the file directly
// keeps GROUP_ID / VERSION_NAME / artifactIds consistent across the AAR
// and the plugin without a copy-paste.
val parentProps: Properties = Properties().apply {
    val parentFile = rootDir.parentFile?.resolve("gradle.properties")
    if (parentFile != null && parentFile.exists()) {
        parentFile.inputStream().use { load(it) }
    }
}
val publishGroup: String = parentProps.getProperty("GROUP_ID")
    ?: error("GROUP_ID missing in parent gradle.properties")
val publishVersion: String = parentProps.getProperty("VERSION_NAME")
    ?: error("VERSION_NAME missing in parent gradle.properties")
val pluginArtifactId: String = parentProps.getProperty("PLUGIN_ARTIFACT_ID")
    ?: "deviceintelligence-gradle"
val libraryArtifactId: String = parentProps.getProperty("LIBRARY_ARTIFACT_ID")
    ?: "deviceintelligence"

group = publishGroup
version = publishVersion

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

dependencies {
    // Modern AGP Variant API (8.1+). The plugin only needs the AGP API on the
    // compile classpath; runtime resolution happens in the consumer's build.
    compileOnly("com.android.tools.build:gradle-api:8.13.2")

    // apksig: Google's official APK re-signing library. We use it from
    // InstrumentApkTask (F8) to re-sign the asset-injected APK with the
    // consumer's signingConfig keystore, producing v1+v2+v3 signatures
    // without shelling out to `apksigner`. This is the same library that
    // AGP itself uses internally.
    implementation("com.android.tools.build:apksig:8.13.2")

    // JUnit 5 for plugin unit tests
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

gradlePlugin {
    plugins {
        create("deviceintelligencePlugin") {
            id = "tech.thessemaj.deviceintelligence"
            implementationClass = "tech.thessemaj.deviceintelligence.gradle.DeviceIntelligencePlugin"
            displayName = "DeviceIntelligence"
            description = "DeviceIntelligence orchestrator: build-time fingerprinting, " +
                "manifest injection, and runtime integrity verification. Auto-applies " +
                "the matching DeviceIntelligence runtime AAR so consumers integrate " +
                "with a single plugin id."
        }
    }
}

// Generate PluginVersion.kt + PluginCoordinates.kt on the plugin's source
// set, baking the parent gradle.properties values into the compiled
// plugin classpath. Two side-effects we depend on:
//
//   1. ComputeFingerprintTask + InstrumentApkTask read PluginVersion.VERSION
//      to stamp every consumer's fingerprint.bin with the exact plugin
//      version that minted it. Server-side correlation needs this.
//
//   2. DeviceIntelligencePlugin.apply() reads PluginCoordinates.GROUP_ID
//      / LIBRARY_ARTIFACT_ID / VERSION to auto-add the runtime AAR as an
//      `implementation` dependency on the consumer's project. Same
//      version as the plugin → no plugin-vs-AAR version skew, ever.
val generatedSrcDir = layout.buildDirectory.dir("generated/source/pluginVersion/kotlin")
val generatePluginVersion by tasks.registering {
    inputs.property("group", publishGroup)
    inputs.property("version", publishVersion)
    inputs.property("libraryArtifactId", libraryArtifactId)
    inputs.property("pluginArtifactId", pluginArtifactId)
    outputs.dir(generatedSrcDir)

    doLast {
        val outDir = generatedSrcDir.get().asFile
            .resolve("tech/thessemaj/deviceintelligence/gradle/internal")
        outDir.mkdirs()
        outDir.resolve("PluginCoordinates.kt").writeText(
            """
            // GENERATED. DO NOT EDIT. Regenerated by the
            // `generatePluginVersion` task in deviceintelligence-gradle/build.gradle.kts
            // from the parent build's gradle.properties.
            package tech.thessemaj.deviceintelligence.gradle.internal

            internal object PluginCoordinates {
                const val GROUP_ID: String = "$publishGroup"
                const val VERSION: String = "$publishVersion"
                const val LIBRARY_ARTIFACT_ID: String = "$libraryArtifactId"
                const val PLUGIN_ARTIFACT_ID: String = "$pluginArtifactId"
            }
            """.trimIndent() + "\n"
        )
    }
}

sourceSets["main"].java.srcDir(generatePluginVersion.map { generatedSrcDir })

// `java-gradle-plugin` + `maven-publish` together auto-create:
//   - a `pluginMaven` MavenPublication for the plugin JAR itself
//   - a marker MavenPublication per `gradlePlugin.plugins { create("X") }`
//     entry, with artifactId == `${id}.gradle.plugin`
//
// The marker POM is what makes `id("tech.thessemaj.deviceintelligence") version "X"`
// resolvable for consumers — without it they'd need a `resolutionStrategy`
// dance in their settings.gradle.kts. We override only the JAR publication's
// artifactId + POM metadata; the marker publication is left at its
// auto-generated coordinates so the plugin id mapping stays correct.
afterEvaluate {
    publishing {
        publications.withType<MavenPublication>().configureEach {
            // Common POM applied to BOTH the JAR publication AND the marker.
            pom {
                url.set("https://github.com/iamjosephmj/DeviceIntelligence")
                licenses {
                    license {
                        name.set("Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)")
                        url.set("https://creativecommons.org/licenses/by-nd/4.0/legalcode")
                        distribution.set("repo")
                    }
                }
                developers {
                    developer {
                        id.set("iamjosephmj")
                        name.set("Joseph James")
                        url.set("https://github.com/iamjosephmj")
                    }
                }
                scm {
                    url.set("https://github.com/iamjosephmj/DeviceIntelligence")
                    connection.set("scm:git:git://github.com/iamjosephmj/DeviceIntelligence.git")
                    developerConnection.set("scm:git:ssh://git@github.com/iamjosephmj/DeviceIntelligence.git")
                }
            }
        }

        // Override only the plugin-JAR publication's coordinates + POM
        // name/description. The auto-generated marker publication keeps
        // its `${id}.gradle.plugin` artifactId so plugin resolution works.
        publications.named<MavenPublication>("pluginMaven") {
            artifactId = pluginArtifactId
            pom {
                name.set("DeviceIntelligence Gradle plugin")
                description.set(
                    "Gradle plugin half of DeviceIntelligence. Wires per-variant " +
                        "fingerprint baking + manifest injection at build time, and " +
                        "auto-applies the matching DeviceIntelligence runtime AAR so " +
                        "consumers integrate with a single plugin id and one repo entry."
                )
            }
        }

        repositories {
            System.getenv("GITHUB_REPOSITORY")?.let { gpr ->
                maven {
                    name = "GitHubPackages"
                    url = uri("https://maven.pkg.github.com/$gpr")
                    credentials {
                        username = System.getenv("GITHUB_ACTOR").orEmpty()
                        password = System.getenv("GITHUB_TOKEN").orEmpty()
                    }
                }
            }
        }
    }
}
